<?php

namespace AppBundle\Repository;

/**
 * AfipTipoDocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfipTipoDocumentoRepository extends \Doctrine\ORM\EntityRepository
{
}
