<?php

namespace AppBundle\Repository;

/**
 * AfipCondicionVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfipCondicionVentaRepository extends \Doctrine\ORM\EntityRepository
{
}
