<?php

namespace AppBundle\Repository;

/**
 * AfipDocumentoTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfipDocumentoTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
