<?php

namespace AppBundle\Repository;

/**
 * AfipAlicuotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfipProvinciaRepository extends \Doctrine\ORM\EntityRepository
{
}
