<?php

namespace AppBundle\Repository;

/**
 * AfipIvaCondicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfipIvaCondicionRepository extends \Doctrine\ORM\EntityRepository
{
}
