<?php

namespace AppBundle\Repository;

/**
 * AfipComprobanteTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfipComprobanteTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
