<?php

namespace AppBundle\Repository;

/**
 * AnteojoSolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnteojoSolRepository extends \Doctrine\ORM\EntityRepository
{
}
