<?php

namespace AppBundle\Repository;

/**
 * ArmazonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmazonRepository extends \Doctrine\ORM\EntityRepository
{
}
