<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByTexto($texto) {
        $query = 'SELECT a  FROM AppBundle:Articulo a ';

        if ($texto != '')
            $query .= ' WHERE a.nombre LIKE :texto OR a.apellido LIKE :texto OR a.username LIKE :texto ';

        $query .= ' ORDER BY a.username ASC ';

        $qb = $this->getEntityManager()->createQuery($query);

        if ($texto != '')
            $qb->setParameter('texto','%' . $texto . '%');


        return $qb;
    }
}
