<?php

namespace AppBundle\Repository;

/**
 * ArticuloMarcaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloMarcaRepository extends \Doctrine\ORM\EntityRepository
{
}
