<?php

namespace AppBundle\Repository;

/**
 * ArticuloCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloCategoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
