<?php

namespace AppBundle\Repository;

/**
 * ClientePagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientePagoRepository extends \Doctrine\ORM\EntityRepository
{
}
