<?php

namespace AppBundle\Repository;

/**
 * ComprobanteDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComprobanteDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
