<?php

namespace AppBundle\Repository;

/**
 * ComprobanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComprobanteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTexto_ventas($sucursalId, $texto) {
        $query = 'SELECT u  FROM AppBundle:Comprobante u 
                  INNER JOIN u.cliente c
                  WHERE u.activo = 1 
                  AND u.movimiento = \'venta\' ';

        if ($sucursalId > 0)
            $query .= ' AND u.sucursal = :sucursalId ';

        if ($texto != '')
            $query .= ' AND (c.nombre LIKE :texto OR c.documentoNumero LIKE :texto) ';

        $query .= ' ORDER BY u.id DESC ';

        $em = $this->getEntityManager()->createQuery($query);

        if ($sucursalId > 0)
            $em->setParameter('sucursalId', $sucursalId);

        if ($texto != '')
            $em->setParameter('texto','%' . $texto . '%');
        
        //return $em;
        return $em->getResult();
    }

    public function findByTexto_compras($sucursalId, $texto) {
        $query = 'SELECT u  FROM AppBundle:Comprobante u 
                  INNER JOIN u.proveedor p
                  WHERE u.activo = 1 
                  AND u.movimiento = \'compra\' ';

        if ($sucursalId > 0)
            $query .= ' AND u.sucursal = :sucursalId ';

        if ($texto != '')
            $query .= ' AND (p.nombre LIKE :texto OR p.documentoNumero LIKE :texto) ';

        $query .= ' ORDER BY u.id DESC ';

        $em = $this->getEntityManager()->createQuery($query);

        if ($sucursalId > 0)
            $em->setParameter('sucursalId', $sucursalId);

        if ($texto != '')
            $em->setParameter('texto','%' . $texto . '%');
        
        //return $em;
        return $em->getResult();
    }

	public function findBy_ventasFacturadasGeneral($fecha_desde, $fecha_hasta, $punto_venta) {
        $query = 'SELECT c FROM AppBundle:Comprobante c 
        			WHERE c.activo = 1
                    AND c.movimiento = \'Venta\'
        			AND c.fecha >= :fecha_desde
        			AND c.fecha <= :fecha_hasta
        			AND c.puntoVenta = :punto_venta
                    AND c.caeNumero IS NOT NULL ';

        $qb = $this->getEntityManager()->createQuery($query)
                ->setParameter('fecha_desde', $fecha_desde)
                ->setParameter('fecha_hasta', $fecha_hasta)
                ->setParameter('punto_venta', $punto_venta);

        return $qb->getResult();
    }

    public function count_alicuotas($comprobante) {
        $query = 'SELECT cd FROM AppBundle:ComprobanteDetalle cd
                    WHERE cd.activo = 1
                    AND cd.comprobante = :comprobante
                    GROUP BY cd.porcentajeIva ';

        $qb = $this->getEntityManager()->createQuery($query)
                ->setParameter('comprobante', $comprobante);

        return count($qb->getResult());
    }
}

