<?php

namespace AppBundle\Repository;

/**
 * LibroCajaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibroCajaRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByTexto($texto, $sucursalId) {
        $query = 'SELECT c FROM AppBundle:LibroCaja c 
                    WHERE c.activo = 1
                    AND c.sucursal = :sucursalId ';

        //Quiero que se vean activos e inactivos con el fin de evitar el borrado de medicos.
        //$query .= 'WHERE c.activo = 1';
        
        $texto != '';

        if ($texto != '')
            $query .= ' AND c.fecha = :texto';

        $query .= ' ORDER BY c.fecha DESC ';

        $em = $this->getEntityManager()->createQuery($query);

        $em->setParameter('sucursalId', $sucursalId);

        if ($texto != '')
            $em->setParameter('texto','%' . $texto . '%');

        return $em;
    }
}
