<?php

namespace AppBundle\Repository;

/**
 * LibroCajaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibroCajaRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByTexto($texto, $sucursalId) {
        $query = 'SELECT c FROM AppBundle:LibroCaja c 
                    WHERE c.activo = 1
                    AND c.sucursal = :sucursalId ';
        
        if (strtotime($texto) > 0)
            $query .= ' AND c.fecha = :texto';

        $query .= ' ORDER BY c.fecha DESC ';

        $em = $this->getEntityManager()->createQuery($query);

        $em->setParameter('sucursalId', $sucursalId);

        if (strtotime($texto) > 0) {
            $fecha = new \DateTime($texto);
            $em->setParameter('texto',$fecha->format('Y-m-d'));
        }

        return $em;
    }
}
