<?php

namespace AppBundle\Repository;

/**
 * LibroCajaDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibroCajaDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
