<?php

namespace AppBundle\Repository;

/**
 * MedicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByTexto($texto) {
        $query = 'SELECT c  FROM AppBundle:Medico c ';

        $query .= 'WHERE c.activo = 1';
        
        if ($texto != '')
            $query .= ' AND c.nombre LIKE :texto 
        				OR c.documentoNumero LIKE :texto 
        				OR c.email LIKE :texto 
        				OR c.contacto LIKE :texto ';

        $query .= ' ORDER BY c.nombre ASC ';

        $em = $this->getEntityManager()->createQuery($query);

        if ($texto != '')
            $em->setParameter('texto','%' . $texto . '%');
        return $em;
    }
}
