<?php

namespace AppBundle\Repository;

/**
 * MovimientoInternoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoInternoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTexto($texto) {
        $query = 'SELECT a  FROM AppBundle:MovimientoInterno a
                    INNER JOIN AppBundle:Sucursal so WITH a.sucursalOrigen = so.id
                    INNER JOIN AppBundle:Sucursal sd WITH a.sucursalDestino = sd.id
                    INNER JOIN AppBundle:MovimientoCategoria mc WITH a.movimientoCategoria = mc.id
                    WHERE a.activo = 1 AND so.activo = 1 AND sd.activo = 1 AND mc.activo = 1';

        if ($texto != ''){
            $query .= ' AND (so.nombre LIKE :texto OR sd.nombre LIKE :texto OR mc.nombre LIKE :texto)';
        }

        $query .= ' ORDER BY a.id DESC ';

        $qb = $this->getEntityManager()->createQuery($query);

        if ($texto != '')
            $qb->setParameter('texto','%' . $texto . '%');


        return $qb;
    }
}
