<?php

namespace AppBundle\Repository;

/**
 * ObraSocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObraSocialRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByTexto($texto) {
        $query = 'SELECT c  FROM AppBundle:ObraSocial c ';
        
        if ($texto != '')
            $query .= ' WHERE c.nombre LIKE :texto';

        $query .= ' ORDER BY c.nombre ASC ';

        $em = $this->getEntityManager()->createQuery($query);

        if ($texto != '')
            $em->setParameter('texto','%' . $texto . '%');
        return $em;
    }
}
