<?php

namespace AppBundle\Repository;

/**
 * ObraSocialPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObraSocialPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
