<?php

namespace AppBundle\Repository;

/**
 * OrdenTrabajoContactologiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenTrabajoContactologiaRepository extends \Doctrine\ORM\EntityRepository
{
	
}
