<?php

namespace AppBundle\Repository;

/**
 * OrdenTrabajoDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenTrabajoDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
