<?php

namespace AppBundle\Repository;

/**
 * OrdenTrabajoContactologiaDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenTrabajoContactologiaDetalleRepository extends \Doctrine\ORM\EntityRepository
{
	
}
