<?php

namespace AppBundle\Repository;

/**
 * OrdenPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenPagoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByTexto($sucursalId, $texto) {
        $query = 'SELECT u  FROM AppBundle:OrdenPago u 
                  INNER JOIN u.proveedor p
                  WHERE u.activo = 1 ';

        if ($sucursalId > 0)
            $query .= ' AND u.sucursal = :sucursalId ';

        if ($texto != '')
            $query .= ' AND (p.nombre LIKE :texto OR p.documentoNumero LIKE :texto) ';

        $query .= ' ORDER BY u.id DESC ';

        $em = $this->getEntityManager()->createQuery($query);

        if ($sucursalId > 0)
            $em->setParameter('sucursalId', $sucursalId);

        if ($texto != '')
            $em->setParameter('texto','%' . $texto . '%');
        
        //return $em;
        return $em->getResult();
    }
}
