<?php

namespace AppBundle\Repository;

/**
 * OrdenPagoComprobanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenPagoComprobanteRepository extends \Doctrine\ORM\EntityRepository
{
}
