<?php

namespace AppBundle\Repository;

/**
 * OrdenTrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenTrabajoRepository extends \Doctrine\ORM\EntityRepository
{
}
