<?php

namespace AppBundle\Repository;

/**
 * OrdenPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
