<?php

namespace AppBundle\Repository;

/**
 * PagoTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagoTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
