<?php

namespace AppBundle\Repository;

/**
 * PedidoDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
