<?php

namespace AppBundle\Repository;

/**
 * PresupuestoDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresupuestoDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
