<?php

namespace AppBundle\Repository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByTexto($texto) {
        $query = 'SELECT p  FROM AppBundle:Producto p ';

        $query .= 'WHERE p.activo = 1';
        
        if ($texto != '')
            $query .= ' AND p.modelo LIKE :texto 
        				OR p.descripcion LIKE :texto';
        				//OR p.categoria LIKE :texto';

        $query .= ' ORDER BY p.descripcion ASC ';

        $em = $this->getEntityManager()->createQuery($query);

        if ($texto != '')
            $em->setParameter('texto','%' . $texto . '%');
        return $em;
    }
}
