<?php

namespace AppBundle\Repository;

/**
 * ProveedorPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
