<?php

namespace AppBundle\Repository;

/**
 * PuntoVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuntoVentaRepository extends \Doctrine\ORM\EntityRepository
{
}
