<?php

namespace AppBundle\Repository;

/**
 * PuntoVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuntoVentaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTexto($texto) {
        $query = 'SELECT a  FROM AppBundle:PuntoVenta a ';

        if ($texto != ''){
            $query .= ' WHERE a.numero LIKE :texto';
        }

        $query .= ' ORDER BY a.numero ASC ';

        $qb = $this->getEntityManager()->createQuery($query);

        if ($texto != '')
            $qb->setParameter('texto','%' . $texto . '%');


        return $qb;
    }
}
