<?php

namespace AppBundle\Repository;

/**
 * ReciboComprobanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReciboComprobanteRepository extends \Doctrine\ORM\EntityRepository
{
}
