<?php

namespace AppBundle\Repository;

/**
 * ReciboRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReciboRepository extends \Doctrine\ORM\EntityRepository
{
}
