<?php

namespace AppBundle\Repository;

/**
 * RolFuncionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolFuncionRepository extends \Doctrine\ORM\EntityRepository
{
}
