<?php

namespace AppBundle\Repository;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTexto($texto) {
        $query = 'SELECT s FROM AppBundle:Stock s ';
        $query.= ' INNER JOIN AppBundle:Articulo a WITH s.articulo = a.id';
        $query.= ' INNER JOIN AppBundle:ArticuloMarca am WITH a.marca = am.id';
        $query.= ' INNER JOIN AppBundle:Sucursal su WITH s.sucursal = su.id';

        $query .= ' WHERE a.activo = 1';

        if ($texto != ''){
            $query .= ' AND (su.nombre LIKE :texto OR a.codigo LIKE :texto OR a.descripcion LIKE :texto OR am.descripcion LIKE :texto)';
         }

        $query .= ' ORDER BY a.descripcion ASC, su.nombre ASC ';

        $qb = $this->getEntityManager()->createQuery($query);

        if ($texto != '')
            $qb->setParameter('texto','%' . $texto . '%');

        return $qb;
    }
}
