<?php

namespace AppBundle\Repository;

/**
 * SucursalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SucursalRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTexto($texto) {
        $query = 'SELECT a  FROM AppBundle:Sucursal a ';

        if ($texto != ''){
            $query .= ' WHERE a.nombre LIKE :texto';
        }

        $query .= ' ORDER BY a.nombre ASC ';

        $qb = $this->getEntityManager()->createQuery($query);

        if ($texto != '')
            $qb->setParameter('texto','%' . $texto . '%');


        return $qb;
    }
}
