<?php

namespace AppBundle\Repository;

/**
 * TallerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TallerRepository extends \Doctrine\ORM\EntityRepository
{
}
