app_recibo_comprobante:
    resource: "@AppBundle/Controller/ReciboComprobanteController.php"
    type:     annotation

app_recibo_comprobante:
    resource: "@AppBundle/Controller/ReciboComprobanteController.php"
    type:     annotation

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /