comprobantedetalle_index:
    path:     /
    defaults: { _controller: "AppBundle:ComprobanteDetalle:index" }
    methods:  GET

comprobantedetalle_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ComprobanteDetalle:show" }
    methods:  GET

comprobantedetalle_new:
    path:     /new
    defaults: { _controller: "AppBundle:ComprobanteDetalle:new" }
    methods:  [GET, POST]

comprobantedetalle_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ComprobanteDetalle:edit" }
    methods:  [GET, POST]

comprobantedetalle_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ComprobanteDetalle:delete" }
    methods:  [GET, POST] 
