informe_afipventasalicuotas:
    path:     /afipventasalicuotas
    defaults: { _controller: "AppBundle:Informe:afipventasalicuotas" }
    methods:  [GET, POST]

informe_afipventasalicuotasexportar:
    path:     /afipventasalicuotasexportar
    defaults: { _controller: "AppBundle:Informe:afipventasalicuotasexportar" }
    methods:  [GET, POST]    

informe_ivadebitocredito:
    path:     /ivadebitocredito
    defaults: { _controller: "AppBundle:Informe:ivadebitocredito" }
    methods:  [GET, POST]
    
informe_gastos:
    path:     /gastos
    defaults: { _controller: "AppBundle:Informe:gastos" }
    methods:  [GET, POST]
    
informe_recibosVentasMedicos:
    path:     /recibosVentasMedicos
    defaults: { _controller: "AppBundle:Informe:recibosVentasMedicos" }
    methods:  [GET, POST]