librocaja_index:
    path:     /
    defaults: { _controller: "AppBundle:LibroCaja:index" }
    methods:  GET

librocaja_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:LibroCaja:show" }
    methods:  GET

librocaja_new:
    path:     /new
    defaults: { _controller: "AppBundle:LibroCaja:new" }
    methods:  [GET, POST]

librocaja_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:LibroCaja:edit" }
    methods:  [GET, POST]

librocaja_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:LibroCaja:delete" }
    methods:  DELETE
