movimientointerno_index:
    path:     /
    defaults: { _controller: "AppBundle:MovimientoInterno:index" }
    methods:  GET

movimientointerno_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:MovimientoInterno:show" }
    methods:  GET

movimientointerno_new:
    path:     /new
    defaults: { _controller: "AppBundle:MovimientoInterno:new" }
    methods:  [GET, POST]

movimientointerno_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:MovimientoInterno:edit" }
    methods:  [GET, POST]

movimientointerno_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:MovimientoInterno:delete" }
    methods:  [GET, POST]
