ordentrabajodetalle_index:
    path:     /
    defaults: { _controller: "AppBundle:OrdenTrabajoDetalle:index" }
    methods:  GET

ordentrabajodetalle_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:OrdenTrabajoDetalle:show" }
    methods:  GET

ordentrabajodetalle_new:
    path:     /new
    defaults: { _controller: "AppBundle:OrdenTrabajoDetalle:new" }
    methods:  [GET, POST]

ordentrabajodetalle_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:OrdenTrabajoDetalle:edit" }
    methods:  [GET, POST]

ordentrabajodetalle_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:OrdenTrabajoDetalle:delete" }
    methods:  [GET, POST] 
