parametro_index:
    path:     /
    defaults: { _controller: "AppBundle:Parametro:index" }
    methods:  GET

parametro_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Parametro:show" }
    methods:  GET

parametro_new:
    path:     /new
    defaults: { _controller: "AppBundle:Parametro:new" }
    methods:  [GET, POST]

parametro_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Parametro:edit" }
    methods:  [GET, POST]

parametro_elegirparametro:
    path:     /elegirparametro
    defaults: { _controller: "AppBundle:Parametro:elegirParametro" }
    methods:  [GET, POST]

parametro_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Parametro:delete" }
    methods:  [GET, POST]

parametro_find_select2:
    path:     /findSelect2
    defaults: { _controller: "AppBundle:Parametro:findSelect2" }

parametro_find:
    path:     /find
    defaults: { _controller: "AppBundle:Parametro:find" }

