pedido_index:
    path:     /
    defaults: { _controller: "AppBundle:Pedido:index" }
    methods:  GET

pedido_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Pedido:show" }
    methods:  GET

pedido_new:
    path:     /new
    defaults: { _controller: "AppBundle:Pedido:new" }
    methods:  [GET, POST]

pedido_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Pedido:edit" }
    methods:  [GET, POST]

pedido_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Pedido:delete" }
    methods:  DELETE

pedido_imprimir:
    path:     /{id}/imprimir
    defaults: { _controller: "AppBundle:Pedido:imprimir" }
    methods:  [GET, POST]