pedidodetalle_index:
    path:     /
    defaults: { _controller: "AppBundle:PedidoDetalle:index" }
    methods:  GET

pedidodetalle_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:PedidoDetalle:show" }
    methods:  GET

pedidodetalle_new:
    path:     /new
    defaults: { _controller: "AppBundle:PedidoDetalle:new" }
    methods:  [GET, POST]

pedidodetalle_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:PedidoDetalle:edit" }
    methods:  [GET, POST]

pedidodetalle_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:PedidoDetalle:delete" }
    methods:  DELETE
