rol_index:
    path:     /
    defaults: { _controller: "AppBundle:Rol:index" }
    methods:  GET

rol_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Rol:show" }
    methods:  GET

rol_new:
    path:     /new
    defaults: { _controller: "AppBundle:Rol:new" }
    methods:  [GET, POST]

rol_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Rol:edit" }
    methods:  [GET, POST]

rol_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Rol:delete" }
    methods:  [GET, POST]

rol_update:
    path:     /update
    defaults: { _controller: "AppBundle:Rol:update" }





