rolfuncion_index:
    path:     /
    defaults: { _controller: "AppBundle:RolFuncion:index" }
    methods:  GET

rolfuncion_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:RolFuncion:show" }
    methods:  GET

rolfuncion_new:
    path:     /new
    defaults: { _controller: "AppBundle:RolFuncion:new" }
    methods:  [GET, POST]

rolfuncion_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:RolFuncion:edit" }
    methods:  [GET, POST]

rolfuncion_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:RolFuncion:delete" }
    methods:  [GET, POST]