sucursal_index:
    path:     /
    defaults: { _controller: "AppBundle:Sucursal:index" }
    methods:  GET

sucursal_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Sucursal:show" }
    methods:  GET

sucursal_new:
    path:     /new
    defaults: { _controller: "AppBundle:Sucursal:new" }
    methods:  [GET, POST]

sucursal_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Sucursal:edit" }
    methods:  [GET, POST]

sucursal_elegirsucursal:
    path:     /elegirsucursal
    defaults: { _controller: "AppBundle:Sucursal:elegirSucursal" }
    methods:  [GET, POST]    

sucursal_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Sucursal:delete" }
    methods:  [GET, POST] 
