taller_index:
    path:     /
    defaults: { _controller: "AppBundle:Taller:index" }
    methods:  GET

taller_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Taller:show" }
    methods:  GET

taller_new:
    path:     /new
    defaults: { _controller: "AppBundle:Taller:new" }
    methods:  [GET, POST]

taller_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Taller:edit" }
    methods:  [GET, POST]

taller_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Taller:delete" }
    methods:  [GET, POST]
