homepage:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }  

app_usuario:
    resource: "@AppBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

app_load:
    resource: "@AppBundle/Resources/config/routing/load.yml"
    prefix:   /acceso
