homepage:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }  

dashboard:
    path:     /dashboard
    defaults: { _controller: "AppBundle:Dashboard:index" }  

app_usuario:
    resource: "@AppBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

app_load:
    resource: "@AppBundle/Resources/config/routing/load.yml"
    prefix:   /acceso

app_proveedor:
    resource: "@AppBundle/Resources/config/routing/proveedor.yml"
    prefix:   /proveedor